In [1]:
import pandas as pd
df=pd.read_csv("D:\\BBAU\\BBAU\\train.csv")

In [2]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       500.000000         500.000000  482.000000        486.000000   
mean       5493.644000        1506.307840  144.020747        342.543210   
std        6515.668972        2134.432188   82.344919         63.834977   
min         150.000000           0.000000   17.000000         12.000000   
25%        2874.500000           0.000000  100.000000        360.000000   
50%        3854.000000        1125.500000  126.500000        360.000000   
75%        5764.000000        2253.250000  161.500000        360.000000   
max       81000.000000       20000.000000  700.000000        480.000000   

       Credit_History  
count      459.000000  
mean         0.843137  
std          0.364068  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [2]:
df.shape

(500, 13)

In [3]:
#There are some NULL data in few columns
#X-Features and y-outcome
X=df.drop(['Loan_Status','Loan_ID'], axis=1)
y=df['Loan_Status']


In [5]:
X.shape

(500, 11)

In [13]:
X.isnull().sum()

Gender                0
Married               0
Dependents           12
Education             0
Self_Employed        27
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           18
Loan_Amount_Term     14
Credit_History       41
Property_Area         0
dtype: int64

In [4]:
X['Gender'].value_counts()

Male      400
Female     91
Name: Gender, dtype: int64

In [5]:
X['Gender'].fillna("Male", inplace=True)

In [6]:
X['Married'].value_counts()

Yes    322
No     175
Name: Married, dtype: int64

In [7]:
X['Married'].fillna("Yes", inplace=True)

In [8]:
X['Dependents'].value_counts()

0     288
1      81
2      79
3+     40
Name: Dependents, dtype: int64

In [9]:
X['Dependents'].fillna(0,inplace=True)

In [10]:
X['Self_Employed'].value_counts()

No     407
Yes     66
Name: Self_Employed, dtype: int64

In [11]:
X['Self_Employed'].fillna('No',inplace=True)


In [12]:
mean_loan=X['LoanAmount'].mean()
X['LoanAmount'].fillna(mean_loan,inplace=True)
X.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       41
Property_Area         0
dtype: int64

In [13]:
X['Loan_Amount_Term'].fillna(X['Loan_Amount_Term'].mean(),inplace=True)

X['Credit_History'].fillna(X['Credit_History'].mean(),inplace=True)

X.isnull().sum()


Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [14]:
X=pd.get_dummies(X)

In [15]:
X.shape

(500, 21)

In [16]:
X.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  144.020747             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
0             1.0              0            1           1            0   
1             1.0              0            1           0            1   
2             1.0              0            1           0            1   
3             1.0              0            1           0            1   
4             1.0              0            1           1            0   

   Dependents_0  ...  Dependents_1  Dependents_2  Dependents_3+  \
0             0  ...             0             0              0   
1             0  ...             1             0              0   
2             0  ...             0             0              0   
3             0  ...             0             0              0   
4             0  ...             0             0              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                   1                       0                 1   
1                   1                       0                 1   
2                   1                       0                 0   
3                   0                       1                 1   
4                   1                       0                 1   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                  0                    0                        0   
1                  0                    1                        0   
2                  1                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    0  
2                    1  
3                    1  
4                    1  

[5 rows x 21 columns]

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.30,random_state=40)


In [18]:
X_train.shape

(350, 21)

In [19]:
X_test.shape

(150, 21)

In [20]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(X_train,y_train)




LogisticRegression()

In [28]:
#model is ML model for this problem
y_predict=model.predict(X_test)
print(y_predict)

['Y' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y'
 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'N' 'Y' 'Y' 'N' 'Y']


In [30]:
df1=pd.DataFrame({"Actual": y_test,"Predicted":y_predict })
df1.to_csv("10_Sep_Output.csv")
#df1.head()

In [31]:
#Score=Correct Outcome/Total Test data size
#For example, if 120 is correct prediction out of 150
#score is =120/150=0.80
s=model.score(X_test,y_test)
print(s)

0.7733333333333333


In [64]:
#116 prediction is correct and 34 prediction is wrong
#Score tells the quality of the model
from sklearn.svm import SVC
svc = SVC()

svc.fit(X, y)


SVC()

In [65]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()

dtc.fit(X_train, y_train)


DecisionTreeClassifier()

In [66]:
from sklearn.naive_bayes import GaussianNB

n_b = GaussianNB()

n_b.fit(X_train, y_train)


GaussianNB()

In [67]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()  

knn.fit(X_train, y_train)


KNeighborsClassifier()

In [68]:
print(lr.score(X_test, y_test))

print(dtc.score(X_test, y_test))

print(n_b.score(X_test, y_test))

print(knn.score(X_test, y_test))

print(svc.score(X_test, y_test))
#Score of 1 is best possible score

0.8466666666666667
0.6933333333333334
0.7466666666666667
0.6533333333333333
0.6933333333333334


In [ ]:
#Logistic Regression (lr) is best model
#why at each instance score is changing?
#Answer is : because of random split each time
#How to control it?
#Answer: set Random_State to any fix value


In [69]:
#Deployment of Model:
gender=input("What is your gender:")
married=input("Married:")
dependents=int(input("dependents value:"))
Education=input("enter your education")
SelfEmployed=input("Self Employed:")
Applicantincome=int(input("enter applicant income"))
coapplicantincome=int(input("enter co applicant income:"))
loanamount=int(input("enter loan amount:"))
loanamountterm=int(input("enter loan amount term:"))
credithistory=int(input("enter credit history:"))
propertyarea=input("enter property area:")
data = [[gender,married,dependents,Education,SelfEmployed,Applicantincome,coapplicantincome,loanamount,loanamountterm,credithistory,propertyarea]]


What is your gender:Male
Married:Yes
dependents value:2
enter your educationGraduate
Self Employed:Yes
enter applicant income7000
enter co applicant income:0
enter loan amount:300
enter loan amount term:240
enter credit history:1
enter property area:Urban


In [70]:
print(data)

[['Male', 'Yes', 2, 'Graduate', 'Yes', 7000, 0, 300, 240, 1, 'Urban']]


In [71]:
#the number of features/columns on which the model has been trained
#it can predict only on that kind of input i.e. input with 21 features
X_train.shape

(350, 21)

In [72]:
y_p=lr.predict(data)

C:\Users\NIELIT\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)


ValueError: X has 11 features per sample; expecting 21

In [74]:
newdf = pd.DataFrame(data, columns = ['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area'])

newdf.head()
#newdf=pd.get_dummies(data)

Gender Married  Dependents Education Self_Employed  ApplicantIncome  \
0   Male     Yes           2  Graduate           Yes             7000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0         300               240               1   

  Property_Area  
0         Urban

In [76]:
newdf=pd.get_dummies(newdf)

In [78]:
newdf.head()

Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0           2             7000                  0         300   

   Loan_Amount_Term  Credit_History  Gender_Male  Married_Yes  \
0               240               1            1            1   

   Education_Graduate  Self_Employed_Yes  Property_Area_Urban  
0                   1                  1                    1

In [79]:
# newdf still not matching 21 columns as required
#what is solution
print(X_train.columns)

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male',
       'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_0',
       'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate',
       'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes',
       'Property_Area_Rural', 'Property_Area_Semiurban',
       'Property_Area_Urban'],
      dtype='object')


In [80]:
print(newdf.columns)

Index(['Dependents', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Gender_Male', 'Married_Yes',
       'Education_Graduate', 'Self_Employed_Yes', 'Property_Area_Urban'],
      dtype='object')


In [81]:
missing_cols=set(X_train.columns)-set(newdf.columns)
print(missing_cols)

{'Property_Area_Rural', 'Property_Area_Semiurban', 'Gender_Female', 'Married_No', 'Dependents_3+', 'Self_Employed_No', 'Dependents_2', 'Dependents_1', 'Education_Not Graduate', 'Dependents_0'}


In [82]:
for i in missing_cols:
    newdf[i]=0

In [83]:
newdf.shape

(1, 21)

In [84]:
newdf.head()

Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0           2             7000                  0         300   

   Loan_Amount_Term  Credit_History  Gender_Male  Married_Yes  \
0               240               1            1            1   

   Education_Graduate  Self_Employed_Yes  ...  Property_Area_Rural  \
0                   1                  1  ...                    0   

   Property_Area_Semiurban  Gender_Female  Married_No  Dependents_3+  \
0                        0              0           0              0   

   Self_Employed_No  Dependents_2  Dependents_1  Education_Not Graduate  \
0                 0             0             0                       0   

   Dependents_0  
0             0  

[1 rows x 21 columns]

In [86]:
y_p=lr.predict(newdf)
print(y_p)

['Y']


In [88]:
if (y_p[0]=='Y'):
    print("Your Loan is approved, Please contact at HDFC Bank Any Branch for further processing")
else:
    print("Sorry ! Your Loan is not approved")


Your Loan is approved, Please contact at HDFC Bank Any Branch for further processing


In [22]:
print(lr.score(X_test,y_test))

0.8466666666666667


In [26]:
y_predict=lr.predict(X_test)
print(y_predict)

['Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y'
 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'N' 'N' 'Y' 'Y' 'N'
 'N' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y'
 'Y' 'Y' 'Y' 'N' 'Y' 'Y']


In [63]:
from sklearn.metrics import confusion_matrix,accuracy_score
a=confusion_matrix(y_test,y_predict)
print(a)

[[35 12]
 [45 58]]


In [25]:
#How confusion Matrix can be changed with regard to customer requirement


y_pr=lr.predict_proba(X_test)
print(y_pr)

[[0.18922674 0.81077326]
 [0.09514422 0.90485578]
 [0.10404162 0.89595838]
 [0.07418924 0.92581076]
 [0.26290918 0.73709082]
 [0.22576529 0.77423471]
 [0.08541357 0.91458643]
 [0.11946034 0.88053966]
 [0.49172326 0.50827674]
 [0.31437792 0.68562208]
 [0.20445098 0.79554902]
 [0.18911188 0.81088812]
 [0.19939686 0.80060314]
 [0.62841941 0.37158059]
 [0.86468196 0.13531804]
 [0.40212714 0.59787286]
 [0.17876171 0.82123829]
 [0.08423422 0.91576578]
 [0.37949653 0.62050347]
 [0.75536412 0.24463588]
 [0.20157094 0.79842906]
 [0.21314505 0.78685495]
 [0.19768808 0.80231192]
 [0.31053614 0.68946386]
 [0.3059084  0.6940916 ]
 [0.42218331 0.57781669]
 [0.2571007  0.7428993 ]
 [0.82441802 0.17558198]
 [0.09181579 0.90818421]
 [0.35160821 0.64839179]
 [0.64216591 0.35783409]
 [0.50063148 0.49936852]
 [0.15451464 0.84548536]
 [0.20456936 0.79543064]
 [0.29952641 0.70047359]
 [0.27581718 0.72418282]
 [0.17144329 0.82855671]
 [0.30385633 0.69614367]
 [0.80347181 0.19652819]
 [0.23103702 0.76896298]


In [52]:
#By default 0.5 is probabilty to decide a Label(Yes or No)
#Set probability for Yes to be greater than 0.75(Not 0.5) to give Yes Label
#this is called threshold=0.75 for deciding Yes or No
def make_class(threshold,y_pro):
    y_predict=[]
    for i in y_pro:
        if(i[1]>threshold):
            y_predict.append('Y')
        else:
            y_predict.append('N')
    return y_predict

y_p_75=make_class(0.45,y_pr)
b=confusion_matrix(y_test,y_p_75)
print(b)
#on threshold of 0.45, bank will not loose any business
#22/47=0.46 or 46% burden reduced

[[ 22  25]
 [  0 103]]


In [61]:
y_p_75=make_class(0.92,y_pr)
b=confusion_matrix(y_test,y_p_75)
print(b)
#on threshold of 0.45, bank will not loose any business
#22/47=0.46 or 46% burden reduced

[[47  0]
 [98  5]]


In [64]:
s=accuracy_score(y_test,y_p_75)
print(s)

0.3466666666666667


In [65]:
print(52/150)

0.3466666666666667
