In [2]:
import myfirstmodule
myfirstmodule.greeting("Ravi")
myfirstmodule.sum(10,20)
myfirstmodule.sum(45,35)

Hello  Ravi
30
80


In [3]:
#have small name instead of large name
import myfirstmodule as my
my.greeting("Ravi")
my.sum(10,20)
my.sum(45,35)


Hello  Ravi
30
80


In [4]:
my.greeting("Mohan")

Hello  Mohan


In [5]:
from myfirstmodule import *
sum(34,23)

57


In [6]:
greeting("Mohan")

Hello  Mohan


In [7]:
#you can import just one function from module
from myfirstmodule import sum
sum(34,20)

54


In [8]:
#NUMpy Array
import numpy as np
a=np.array([10,20,30])
print(a)


[10 20 30]


In [9]:
print(a.dtype)

int32


In [10]:
print(a.shape)

(3,)


In [11]:
print(a.size)

3


In [13]:
#Two dimensional Array
b=np.array([[10,20],[3,4],[5,6]])
print(b)

[[10 20]
 [ 3  4]
 [ 5  6]]


In [14]:
print(b.shape)

(3, 2)


In [15]:
print(b.size)

6


In [16]:
#Reshaping any array into any form
c=b.reshape(2,3)
print(c)

[[10 20  3]
 [ 4  5  6]]


In [19]:
b=np.array([[10,20],[3,4],[5,6]])
print(b)
print(b[1,1]) #Slicing

[[10 20]
 [ 3  4]
 [ 5  6]]
4


In [25]:
b=np.array([[10,20],[3,40],[5,6]])
print(b)
print(b.max())
print(b.max(axis=0)) #axis=0 means column wise
print(b.max(axis=1)) #axis=1 means row wise

[[10 20]
 [ 3 40]
 [ 5  6]]
40
[10 40]
[20 40  6]


In [26]:
print(b.min())
print(b.min(axis=1)) #row wise operation

3
[10  3  5]


In [22]:
print(b.sum())

48


In [27]:
#Sum of two dimensional arrays
a=np.array([[1,2,30],[10,15,4]])
b=np.array([[10,20,30],[40,50,60]])
print(a+b)

[[11 22 60]
 [50 65 64]]


In [29]:
a=np.zeros((3,2),dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [30]:
a=np.ones((3,2),dtype=int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


In [32]:
#Converting tuple into array
i=(1,2,3,4,5)
a=np.asarray(i)
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [34]:
#convert dictionary in array
d={"name":"Ravi","city":"Lucknow","College":"KGMC"}
a=np.asarray(d)
print(a)
print(type(a))

{'name': 'Ravi', 'city': 'Lucknow', 'College': 'KGMC'}
<class 'numpy.ndarray'>


In [35]:
#arange(start,stop,step)
a=np.arange(2,10,2)
print(a)

[2 4 6 8]


In [40]:
a=np.array([[1,2,30],[10,15,4]])
sum=0
for x in np.nditer(a):
    print(x)
    sum=sum+x
print("sum:",sum)

1
2
30
10
15
4
sum: 62


In [41]:
#When Order is F(Fortran like), It means column-wise data will be read
a=np.array([[1,2,30],[10,15,4]])
print(a)
for x in np.nditer(a,order='F'):
    print(x)


[[ 1  2 30]
 [10 15  4]]
1
10
2
15
30
4


In [42]:
#When Order is C(C language like), It means row-wise data will be read
a=np.array([[1,2,30],[10,15,4]])
print(a)
for x in np.nditer(a,order='C'):
    print(x)


[[ 1  2 30]
 [10 15  4]]
1
2
30
10
15
4


In [43]:
a=np.array([[1.234,2.678,30.456],[10.234,56,73.34]])
print(np.around(a,2))

[[ 1.23  2.68 30.46]
 [10.23 56.   73.34]]


In [44]:
#Sorting row wise
a=np.array([[1,2,30],[10,15,4],[50,40,90]])
print(np.sort(a))

[[ 1  2 30]
 [ 4 10 15]
 [40 50 90]]


In [45]:
#Sorting column wise
a=np.array([[1,2,30],[10,15,4],[50,40,90]])
print(np.sort(a,0))

[[ 1  2  4]
 [10 15 30]
 [50 40 90]]


In [47]:
ap=np.array([2,45,20])
ar=ap # when you copy an array, it is just referenced...no physical copy is made
ar[1]=900
print(ar)
print(ap)


[  2 900  20]
[  2 900  20]
